/* eslint-disable react/no-unescaped-entities */
import { PlainPage, pageMetadata } from "../site";

export const metadata = pageMetadata("Privacy | What TabShow Can and Cannot Access", "Plain-language TabShow privacy policy covering extension permissions, local processing, and consent-based website analytics.", "/privacy");

export default function PrivacyPage() {
  return <PlainPage eyebrow="Privacy by design" title="Your tabs stay" accent="in your browser." lead="TabShow uses Chrome's extension APIs to list and manage tabs. It does not read page contents, send browsing data to a server, or require an account." nav={[{href:"#summary",label:"Plain-language summary"},{href:"#permissions",label:"Permissions"},{href:"#data",label:"Data handling"},{href:"#website-analytics",label:"Website analytics"},{href:"#changes",label:"Policy changes"}]}>
    <section id="summary"><h2>The plain-language summary</h2><p>TabShow runs locally as a Chrome extension. The extension has no TabShow account system, analytics service, advertising system, or backend that receives tab data.</p><ul><li>No account or sign-in.</li><li>No host permissions.</li><li>No access to the contents of webpages.</li><li>No sale, sharing, or transmission of browsing data.</li><li>No analytics or behavioral tracking inside the extension.</li></ul><p>Chrome tab metadata is still sensitive. TabShow reads only what its visible features need and keeps that work inside the browser.</p></section>
    <section id="permissions"><h2>Why TabShow requests each permission</h2><table><thead><tr><th>Permission</th><th>What it enables</th><th>What it does not enable</th></tr></thead><tbody><tr><td><code>sidePanel</code></td><td>Displays TabShow beside the page you are viewing.</td><td>It does not grant access to page contents.</td></tr><tr><td><code>tabs</code></td><td>Reads open-tab titles, URLs, favicons, window membership, and status so TabShow can list, search, sort, preview, switch, and close tabs.</td><td>It does not grant access to the DOM, text, forms, or network traffic inside a webpage.</td></tr><tr><td><code>tabGroups</code></td><td>Reads group names, colors, membership, and collapsed state so Chrome groups can be represented in the side panel.</td><td>It does not create a TabShow cloud workspace or send group data elsewhere.</td></tr><tr><td><code>favicon</code></td><td>Uses Chrome's local favicon cache when a tab does not provide a usable icon.</td><td>It does not contact websites on TabShow's behalf.</td></tr></tbody></table><p>The previously declared <code>activeTab</code> permission was removed in 2.0 because the implementation did not use it. TabShow 2.1 adds no permissions.</p></section>
    <section id="data"><h2>What is stored</h2><p>TabShow stores user settings such as color pairing, hover-preview delay, appearance, and current-window versus all-window scope in Chrome's local browser storage. These settings do not contain copies of webpage content.</p><p>The Tab Chaos trend stores up to 90 local daily check-ins. Repeated panel openings update the current day's check-in instead of adding another record. Each check-in contains a timestamp, local calendar day, derived score, and open-tab count. The same local record retains the all-time best score. It does not store tab titles, URLs, domains, favicons, or page contents. Older daily check-ins are removed as new ones are added, while the all-time best is retained. You can delete this history by clearing TabShow's extension data in Chrome or uninstalling the extension.</p><h3>What is processed temporarily</h3><p>Open-tab metadata and group information are processed to render the list, search results, sorting, indicators, preview state, actions you request, and the current Tab Chaos summary. The extension reacts to Chrome tab and window events so the panel stays current.</p><h3>What is transmitted</h3><p>The extension code has no TabShow backend endpoint for tab information. Clicking an external link, such as the Chrome Web Store, support site, or public Featurebase board, opens that destination under its own privacy terms.</p></section>
    <section id="website-analytics"><h2>Website analytics</h2><p>The public <code>tab.show</code> website uses Google Analytics 4 only after you select <strong>Allow analytics</strong>. If you decline, the Google Analytics tag is not loaded.</p><p>When allowed, Google Analytics may process page views, navigation and interaction events, referral information, approximate location, and browser or device information. It uses a first-party <code>_ga</code> cookie to distinguish website visitors and sessions. Advertising storage, advertising user data, ad personalization, and Google Signals are disabled in TabShow's website configuration.</p><p>This website measurement is separate from the Chrome extension. Tab titles, URLs, favicons, groups, searches, preview activity, and webpage contents are never sent to Google Analytics. You can change your choice at any time using <strong>Analytics settings</strong>.</p><p>Google processes analytics data under its own <a href="https://policies.google.com/privacy">privacy policy</a>.</p></section>
    <section id="changes"><h2>Changes to this policy</h2><p>If a future TabShow release adds extension data collection, an account, remote processing, or a new permission, this page and the Chrome Web Store privacy disclosure must be updated before that release. The policy should always describe the shipped extension, not a marketing aspiration.</p><p><strong>Effective date:</strong> September 1, 2026. <strong>Applies to:</strong> TabShow 2.1 and the <code>tab.show</code> website.</p></section>
  </PlainPage>;
}
