/* eslint-disable react/no-unescaped-entities */
import { FEEDBACK_URL, REVIEW_URL, PlainPage, pageMetadata } from "../site";

export const metadata = pageMetadata("TabShow Support | Setup, Shortcuts, Preview and Feedback", "Get TabShow help for the Chrome side panel, keyboard shortcut, live preview, search, multiple windows, sorting, feedback, and reviews.", "/support");

export default function SupportPage() {
  return <PlainPage eyebrow="Support" title="Get back to the tab" accent="you were looking for." lead="Start with the quick checks below. If something still feels wrong, share the details on the public feedback board so the fix can help everyone." nav={[{href:"#start",label:"Getting started"},{href:"#shortcuts",label:"Keyboard"},{href:"#preview",label:"Preview behavior"},{href:"#troubleshooting",label:"Troubleshooting"},{href:"#contact",label:"Feedback"}]}>
    <section id="start"><h2>Getting started</h2><ol><li>Install TabShow from the Chrome Web Store.</li><li>Pin the TabShow icon if you want one-click access.</li><li>Click the icon or use the extension shortcut to open Chrome's side panel.</li><li>Search a title, URL, or domain, or point at a tab to preview it.</li><li>Click the right tab to switch, or move away to return.</li></ol><p>TabShow opens in Current window scope. Choose All windows when the page may be open elsewhere.</p></section>
    <section id="shortcuts"><h2>Keyboard navigation</h2><p>The default side-panel shortcut is <strong>Shift + Ctrl + X</strong> on Windows and <strong>Shift + Command + X</strong> on macOS. Chrome can override or clear extension shortcuts, so verify yours at <code>chrome://extensions/shortcuts</code>.</p><ul><li><strong>Arrow Down / Arrow Up:</strong> move through and select matching tabs.</li><li><strong>Enter:</strong> open the selected tab.</li><li><strong>Escape:</strong> return to the original tab and close the panel.</li><li><strong>Hover:</strong> preview a current-window tab without committing to the switch.</li></ul></section>
    <section id="preview"><h2>How preview is meant to behave</h2><p>In the current Chrome window, pointing at a tab temporarily activates its live page. The original tab remains marked. Leaving the side panel or closing it restores the original tab unless you clicked a result to make the switch permanent.</p><p>In All windows scope, tabs belonging to another window show a switch indicator. They do not hover-preview. Click one when you intentionally want Chrome to focus that window and tab.</p></section>
    <section id="troubleshooting"><h2>Quick troubleshooting</h2><h3>The side panel does not open</h3><p>Confirm TabShow is enabled at <code>chrome://extensions</code>, then try the toolbar icon. If a shortcut conflicts with another extension, assign a different one in Chrome's shortcut settings.</p><h3>A preview starts too easily</h3><p>Open TabShow settings and increase the hover preview delay. A longer delay reduces accidental previews when the pointer crosses the list.</p><h3>A tab or favicon looks stale</h3><p>Navigate or activate the tab once, then reopen TabShow. If the issue repeats, include the page type, Chrome version, and exact steps in a Featurebase report. Do not post sensitive URLs publicly.</p><h3>Search does not find a page</h3><p>Try a domain or URL fragment, and switch to All windows. Search checks the metadata Chrome exposes; it does not search text inside webpages.</p></section>
    <section id="contact"><h2>Feedback and reviews</h2><div className="support-cards"><a href={FEEDBACK_URL} target="_blank" rel="noreferrer"><b>Share feedback ↗</b><span>Suggest a feature, report a problem, comment, or upvote what should be built next.</span></a><a href={REVIEW_URL} target="_blank" rel="noreferrer"><b>Rate TabShow ↗</b><span>If TabShow has earned five stars, a quick Chrome Web Store review helps others find it.</span></a></div><p>Feedback and reviews are separate, voluntary actions. A review never unlocks functionality, and critical feedback belongs on the same public board as feature ideas.</p></section>
  </PlainPage>;
}
